'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { Zap, ArrowRight, Sparkles, Swords, Trophy, BarChart3, Users } from 'lucide-react';

export default function HomePage() {
  return (
    <div className="min-h-screen bg-bg-primary">
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-20 left-10 w-72 h-72 bg-accent-blue/5 rounded-full blur-3xl" />
        <div className="absolute bottom-20 right-10 w-96 h-96 bg-accent-cyan/5 rounded-full blur-3xl" />
      </div>

      <div className="relative z-10">
        <nav className="flex items-center justify-between p-6 max-w-7xl mx-auto">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-accent-blue to-accent-cyan flex items-center justify-center">
              <Zap className="w-5 h-5 text-white" />
            </div>
            <span className="text-lg font-bold gradient-text">Level Up</span>
          </div>
          <div className="flex items-center gap-4">
            <Link
              href="/login"
              className="text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              Sign In
            </Link>
            <Link
              href="/register"
              className="px-4 py-2 rounded-xl bg-gradient-to-r from-accent-blue to-accent-cyan text-white text-sm font-semibold hover:opacity-90 transition-opacity"
            >
              Get Started
            </Link>
          </div>
        </nav>

        <div className="max-w-7xl mx-auto px-6 pt-20 pb-32">
          <div className="text-center max-w-3xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <span className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-medium bg-accent-blue/10 text-accent-blue border border-accent-blue/20 mb-6">
                <Sparkles className="w-3 h-3" />
                AI-Powered Gamified Productivity
              </span>
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1, duration: 0.6 }}
              className="text-5xl md:text-7xl font-bold leading-tight mb-6"
            >
              Turn your life
              <br />
              <span className="gradient-text">into a game</span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.6 }}
              className="text-lg text-text-secondary max-w-xl mx-auto mb-10"
            >
              Level up your life with AI-generated quests, XP rewards, achievements, and streaks. 
              The most engaging productivity platform ever built.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3, duration: 0.6 }}
              className="flex items-center justify-center gap-4"
            >
              <Link
                href="/register"
                className="px-8 py-4 rounded-xl bg-gradient-to-r from-accent-blue to-accent-cyan text-white font-semibold text-lg hover:opacity-90 transition-opacity flex items-center gap-2"
              >
                Start Your Journey
                <ArrowRight className="w-5 h-5" />
              </Link>
              <Link
                href="/login"
                className="px-8 py-4 rounded-xl glass text-text-primary font-semibold text-lg hover:bg-bg-glass-hover transition-colors"
              >
                Sign In
              </Link>
            </motion.div>
          </div>

          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5, duration: 0.6 }}
            className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-32 max-w-5xl mx-auto"
          >
            {[
              {
                icon: Swords,
                title: 'AI Quests',
                desc: 'Personalized tasks generated by AI based on your goals and progress',
                color: 'text-accent-purple',
                bgColor: 'bg-accent-purple/10',
              },
              {
                icon: Trophy,
                title: 'Level & XP',
                desc: 'Earn XP, level up, unlock achievements, and track your streaks',
                color: 'text-accent-orange',
                bgColor: 'bg-accent-orange/10',
              },
              {
                icon: BarChart3,
                title: 'Analytics',
                desc: 'Beautiful charts showing your growth, completion rates, and trends',
                color: 'text-accent-cyan',
                bgColor: 'bg-accent-cyan/10',
              },
            ].map((feature, i) => {
              const Icon = feature.icon;
              return (
                <div key={i} className="glass-hover p-8 text-center">
                  <div className={`w-14 h-14 mx-auto mb-5 rounded-2xl ${feature.bgColor} flex items-center justify-center`}>
                    <Icon className={`w-7 h-7 ${feature.color}`} />
                  </div>
                  <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                  <p className="text-sm text-text-secondary">{feature.desc}</p>
                </div>
              );
            })}
          </motion.div>
        </div>

        <footer className="border-t border-border-subtle py-8">
          <div className="max-w-7xl mx-auto px-6 flex items-center justify-between">
            <p className="text-sm text-text-muted">Level Up &mdash; Turn your life into a game</p>
            <p className="text-sm text-text-muted">&copy; {new Date().getFullYear()}</p>
          </div>
        </footer>
      </div>
    </div>
  );
}
